<?php

declare(strict_types=1);

namespace App\Mcp;

use App\Garmin\Mirror;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Content\Text;
use Throwable;

/**
 * Says so when a tool answer is built on seeded demo data.
 *
 * The Quickstart seeds a generated mirror so the dashboard has something
 * to show before the first real fetch, and the next step many testers
 * take is connecting an AI to it. Without a marker the model reads those
 * rows as the tester's own health record and answers accordingly, in the
 * second person, about a body that does not exist. Every seeded row
 * carries fetched_at='demo' (seed_demo.py refuses to write anywhere
 * else), so the mirror itself can be asked.
 *
 * Asked per call rather than cached: a real fetch can land between two
 * calls of one long-lived stdio session, and the one exists-query on the
 * bookkeeping table costs less than a stale claim about somebody's data
 * source. Stamping must never break a tool call, so every failure path
 * hands the response back untouched.
 */
class DemoNotice
{
    public static function stamp(Response $response): Response
    {
        try {
            if ($response->isError() || ($notice = self::notice()) === null) {
                return $response;
            }

            $content = $response->content();

            if (! $content instanceof Text) {
                return $response;
            }

            $decoded = json_decode((string) $content, true);

            // First key on purpose: a model reads the front of a long
            // answer with more attention than the tail.
            if (is_array($decoded) && ! array_is_list($decoded)) {
                return Response::json(['data_source' => $notice] + $decoded);
            }

            return Response::text($notice."\n\n".(string) $content);
        } catch (Throwable) {
            return $response;
        }
    }

    /**
     * What the bookkeeping table says about where the rows came from.
     *
     * Mixed is a real state, not an edge case: connecting Garmin after
     * seeding overwrites only the days the fetch window reaches, and the
     * older rows stay generated. A blanket "demo data" would then be as
     * wrong as saying nothing.
     */
    private static function notice(): ?string
    {
        $origin = (array) Mirror::connection()->selectOne(
            "select exists(select 1 from fetch_log where fetched_at = 'demo') as demo, "
            ."exists(select 1 from fetch_log where fetched_at is distinct from 'demo') as fetched"
        );

        return match (true) {
            $origin['demo'] && ! $origin['fetched'] => 'This mirror holds seeded demo data, generated by seed_demo.py. '
                .'It is not a real athlete\'s record; read every value as an example, not a finding.',
            $origin['demo'] && $origin['fetched'] => 'This mirror still holds seeded demo rows (fetched_at = \'demo\') '
                .'alongside really fetched data; older dates may be generated examples.',
            default => null,
        };
    }
}
